### ISSUE TITLE
-Daudit.failOnError=false doesn't work

### ISSUE THREAD

**Issue by clausfod** [OSSIndex/ossindex-maven-plugin#1]
Hi,

I've tried using the maven plugin with the parameter audit.failOnError=true without luck.

Build will still fail... Please fix :-)

Kind regards
Claus

**Comment by OSSIndex** [comment]
Thanks very much for the report. I will fix the issue as soon as possible. It is quite a busy week, but I expect I will have it solved before the end of the weekend at the latest. Meanwhile, to ensure that I can properly test, what version of maven are you running and on what platform?

FYI, we have been planning a major overhaul of both the client and server code which should be done reasonably soon. With the upgrade you should see a major increase in speed and also many more reported vulnerabilities (depending of course on what your dependencies are).

**Comment by clausfod** [comment]
Hi,

Thanks for your quick response :-)

We are running Maven 3.3.9 and both Redhat 7.1.x

Thanks in advance.

Kind regards
Claus

**Comment by clausfod** [comment]
BTW: Is the analysis done on transitive dependencies also ?

**Comment by OSSIndex** [comment]
Yes, it should be (assuming that it is not broken). My builds definitely fail due to broken transitive dependencies. I will double check that as well when I am working on this issue just to be certain.

**Comment by clausfod** [comment]
Super - Thanks :-)

**Comment by clausfod** [comment]
It's working now - error on my side

**Comment by OSSIndex** [comment]
That's good to hear, thanks. Meanwhile you have lit a fire under me -- I am improving the test coverage (https://github.com/OSSIndex/ossindex-maven-plugin/issues/2) and completing the port to the new 2.x API (https://github.com/OSSIndex/ossindex-maven-plugin/issues/3).

This second one is particularly important as there are definitely vulnerabilities that are not exposed by the 1,x API (there was a fair amount of database refactoring on the back end to improve things). I plan on completing the upgrade by the end of the weekend and will notify you on its completion.

Thanks for the feedback!

ps. I verified the transitive dependencies are indeed checked.

Ken

**Comment by clausfod** [comment]
Super :-) Thanks :-)
