### ISSUE TITLE
audit output was overwritten when  multiple modules existing

### ISSUE THREAD

**Issue by NancyChunlan** [OSSIndex/ossindex-maven-plugin#13]
We tried to use -Daudit.output in our multiple modules project and found that the output was overwritten in modules. After plugin finished, the output only included the last module. What we need is the output of all modules.
Would you please help to check and fix this issue, or guide us how to set the output in multiple modules' project? Thanks in advance.

**Comment by OSSIndex-Admin** [comment]
I am working on the issue now, and will hopefully have a fix before the end of the night. Sorry for the wait.

**Comment by OSSIndex-Admin** [comment]
Fixed by https://github.com/OSSIndex/ossindex-maven-plugin/commit/d8a835660ceec0b4796c4c0fd57183af9b91c029
