### ISSUE TITLE
Show warning on "ignored" package.

### ISSUE THREAD

**Issue by rhwood** [OSSIndex/ossindex-maven-plugin#15]
Can a configuration option be added to have this plugin to check but show a warning for an ignored package?

I would like to be able to nag about a security concern in a package that we are delaying a change on due to other issues, but still error on an unknown security concern in other, non-ignored packages in a CI environment.

**Comment by OSSIndex-Admin** [comment]
A new options `-Daudit.warnOnIgnore` has been added, which will print out "ignored" vulnerabilities as warnings, in the same format as they would be printed has they not been ignored.

If you use the `-Daudit.quiet` option they are still listed as ignored on the summary line. The summary line does not have "warnings" yet. I am still considering what to do in these situations.

The release for this update is 2.3.7, which has been published on maven central.
