### ISSUE TITLE
Add options to specify audit scope

### ISSUE THREAD

**Issue by OSSIndex-Admin** [OSSIndex/ossindex-maven-plugin#18]
From [#12](https://github.com/OSSIndex/ossindex-maven-plugin/issues/12#issuecomment-324564573)

[It] seems the plugin also scanned 3pps in test scope, is it possible to add new parameters to specify the scope? Thanks!

**Comment by NancyChunlan** [comment]
Any updates for this?

**Comment by OSSIndex-Admin** [comment]
Argh. I completely dropped the ball on this issue. I am looking into the issue now and will endeavour to complete a fix this weekend, all going well. Sorry for the delay.

**Comment by OSSIndex-Admin** [comment]
A brief note on this. I found some sample code that illustrates how to resolve the issue. It is quite straight forward, assuming the example is correct, so I am quite optimistic for a quick turnaround (now that you have re-brought the issue to my attention).

**Comment by OSSIndex-Admin** [comment]
I have added the feature. There is a new property:
```
-Daudit.scope=<scope list>
```

where <scope list> is a comma delimited set of scopes that should be checked, for example:
```
-Daudit.scope=compile,test
```

will audit packages in the compile and test scopes.

Release 2.3.8 is out with this change, but I will be making another release shortly that will contain this information in the `--help` text.

Sorry for the delay, and thanks for the help!

**Comment by museadmin** [comment]
Is it possible to set the proxy when using the cradle plugin? And if not would you consider adding a fix for that as well?

**Comment by OSSIndex-Admin** [comment]
Proxy support was recently added to the gradle plugin. It has been published as a "beta" but works fine. The PR will be merged with the master branch shortly.

**Comment by NancyChunlan** [comment]
@OSSIndex-Admin  Thanks a lot for your update. We have add the property in our project.
