### ISSUE TITLE
Feature request: JUnit reports.

### ISSUE THREAD

**Issue by qacwnfq** [OSSIndex/ossindex-maven-plugin#6]
This project sounds interesting but breaking the build should not be taking lightly.
I'd much more prefer for the creation of JUnit reports. Something like the failsafe-plugin does.
Maybe add a flag like
```
   <maven.ossindex.failOnVulnerability>true</maven.frontend.failOnVulnerability>
```

**Comment by OSSIndex** [comment]
I agree, we should not fail automatically and I will change the default behaviour next release. There is a currently undocumented feature that allows you to disable this behaviour via the command line:

```-Daudit.failOnError=false```

I will look in to how failsafe-plugin implements their behaviour -- thanks for the pointer.

**Comment by ken-duck** [comment]
FYI, there has been a ground up rewrite of this plugin to work with the new OSS Index 3.0 API. This API provides access to many more vulnerabilities. The rewrite can be found here: https://github.com/sonatype/ossindex-maven

This rewrite has kept the default to be fail on error as there appears to be a lot of support for that as the default. Configuring the new plugin's operation can be done via the POM, and it should be easy to change this default behaviour, as seen here: https://sonatype.github.io/ossindex-maven/maven-plugin/failorwarn/

The proper "3.0.0" version of the new plugin should be available within the week. This plugin is being deprecated as it still uses the old API.

**Comment by vveider** [comment]
And how about JUnit reports? Without it using such plugin on CI/CD services is most impracticable.

**Comment by ken-duck** [comment]
Heh. I totally should have closed this issue :D

Meanwhile the new plugin is here: https://github.com/sonatype/ossindex-maven

I will create a feature request for JUnit reports for the new plugin. I agree it would be quite useful.

**Comment by ken-duck** [comment]
New issue: https://github.com/sonatype/ossindex-maven/issues/32
